name: lighthouse

on: [deployment_status]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: treosh/lighthouse-ci-action@9.3.0
        with:
          urls: ${{ github.event.deployment_status.target_url }}
          temporaryPublicStorage: true
          runs: 3
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
