name: lighthouse

on: [push]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vercel:
    if: github.repository_owner == 'ismay'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      url: https://${{ steps.url.outputs.preview_url }}
    steps:
      - uses: zentered/vercel-preview-url@v1.0.7
        id: url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ismaywolff
          vercel_project_id: prj_7ehBOE848tjhgDYu19R2X73IGqzM
      - uses: unlyed/github-action-await-vercel@v1.2.15
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.url.outputs.preview_url }}
          timeout: 600

  lighthouse:
    needs: ["vercel"]
    if: github.repository_owner == 'ismay'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: treosh/lighthouse-ci-action@9.3.0
        with:
          urls: ${{ needs.vercel.outputs.url }}
          budgetPath: ".github/budget.json"
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
